#!/bin/sh
pvput caqtdmDBRstringArray 10 "one" "two" "three" "four" "five" "six" "seven" "eight" "nine" "ten"
pvput caqtdmDBRbyteArray 10 0 1 2 3 4 5 6 7 8 9
pvput caqtdmDBRshortArray 10 0 1 2 3 4 5 6 7 8 9
pvput caqtdmDBRlongArray 10 0 1 2 3 4 5 6 7 8 9
pvput caqtdmDBRfloatArray 10 0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.99
pvput caqtdmDBRdoubleArray 10 0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.99

