TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


PROD_HOST += monitorForever
monitorForever_SRCS += monitorForever.cpp
monitorForever_LIBS += pvaClient pvAccess nt pvData ca Com


#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

