TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this


DB += ai.db
DB += ao.db
DB += array.db
DB += counter.db
DB += longin.db
DB += longout.db
DB += mbbi.db
DB += mbbo.db
DB += bi.db
DB += bo.db
DB += stringArray.db
DB += stringin.db
DB += stringout.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

